version: '3.7'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: hpal
      POSTGRES_USER: hpal
      POSTGRES_MULTIPLE_DATABASES: happypal_technical_test,happypal_technical_test_e2e

    volumes:
      - postgres:/var/lib/postgresql/data
      - ./pg-init-scripts:/docker-entrypoint-initdb.d

volumes:
  postgres:
    name: hpal
